---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[redisio]
      - recipe[redisio::enable]
      - recipe[openresty]
      - recipe[deploygif::default]
    attributes:
      redisio:
        package_install: true
        default_settings: 
          shutdown_save": true
