# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
  config.omnibus.chef_version = :latest
  config.vm.boot_timeout = 120
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "Berksfile"

  config.vm.provision :chef_solo do |chef|
    chef.roles_path = 'roles'
    chef.json = {}
    chef.run_list = [
      "role[deploygif]"
    ]
  end
end
